### ISSUE TITLE
Date format in the tests/clinical_ingest.json

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/candigv2-ingest#88]
Hi there, 

I ran into an issue when I was trying the data ingest. Here is what I did:
 
0) CanDIGv2 is setting up and works fine;
1) I  checked out the 'development' branch of this 'candigv2-ingest';
2) ran `python katsu_ingest.py --input tests/clinical_ingest.json` in a conda env. 

I got the following `date` format related issue. In the date file `tests/clinical_ingest.json`, the date is in format:

```
            "date_of_birth": {
                "month_interval": -768,
                "day_interval": -23376
            },

```

What I missed here? Any suggestion is highly appreciated. 

Thanks,
Ray

```
input string: {'month_interval': 70, 'day_interval': 2100} 
Traceback (most recent call last):
  File "/home/rocky/ingest-candigv2/katsu_ingest.py", line 335, in <module>
    main()
  File "/home/rocky/ingest-candigv2/katsu_ingest.py", line 330, in main
    result, status_code = ingest_clinical_data(ingest_json, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocky/ingest-candigv2/katsu_ingest.py", line 286, in ingest_clinical_data
    schemas_to_ingest = prepare_clinical_data_for_ingest(ingest_json)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocky/ingest-candigv2/katsu_ingest.py", line 252, in prepare_clinical_data_for_ingest
    schema.validate_ingest_map(by_program[program_id])
  File "/home/rocky/CanDIGv2/bin/miniconda3/envs/raycandig/lib/python3.11/site-packages/clinical_etl/schema.py", line 325, in validate_ingest_map
    self.validate_schema(root_schema, map_json[root_schema][x])
  File "/home/rocky/CanDIGv2/bin/miniconda3/envs/raycandig/lib/python3.11/site-packages/clinical_etl/schema.py", line 411, in validate_schema
    eval(f"self.validate_{schema_name}({map_json})")
  File "<string>", line 1, in <module>
  File "/home/rocky/CanDIGv2/bin/miniconda3/envs/raycandig/lib/python3.11/site-packages/clinical_etl/mohschema.py", line 219, in validate_donors
    death = dateparser.parse(map_json["date_of_death"]).date()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocky/CanDIGv2/bin/miniconda3/envs/raycandig/lib/python3.11/site-packages/dateparser/conf.py", line 100, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/rocky/CanDIGv2/bin/miniconda3/envs/raycandig/lib/python3.11/site-packages/dateparser/__init__.py", line 79, in parse
    data = parser.get_date_data(date_string, date_formats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocky/CanDIGv2/bin/miniconda3/envs/raycandig/lib/python3.11/site-packages/dateparser/date.py", line 511, in get_date_data
    raise TypeError("Input type must be str")
TypeError: Input type must be str

``` 

<img width="1091" alt="image" src="https://github.com/CanDIG/candigv2-ingest/assets/7293118/e4d31b3e-8944-4c48-9bb5-bcc06df0efa9">

**Comment by mshadbolt** [comment]
Hi Ray, thanks for reaching out!

It seems like maybe ingest is failing due to a mismatch between wanting string based dates (which we used to use) and integer based date intervals (our latest version).

Can I check what versions of submodules you are using, if you go to your base CanDIGv2 repo, and use the command `git submodule status` and let me know the output?

When you say CanDIGv2 is setting up and working, were you able to run the integration tests by using the command `make test-integration`? Let us know if you have any errors from running that suite of tests as it also ingests the test data from ingest and might help us diagnose what is going wrong. If you want to keep the data in the system after ingesting using the integration tests, ensure the variable `KEEP_TEST_DATA` is set to `true`

**Comment by rjiang9** [comment]
Hi @mshadbolt, 
Thank you so much for the quick response. 

For the `git submodule status`, here is the result:

<img width="672" alt="image" src="https://github.com/CanDIG/candigv2-ingest/assets/7293118/498d3ac9-301f-450e-9d72-385e7c09a35c">

For running `make test-integration`, I got errors (My colleague set this CanDIGv2 up and were not in these days). I am sorry about the inaccurate info above. 

Error file is attached now:
[make-test-integration.txt](https://github.com/CanDIG/candigv2-ingest/files/14984603/make-test-integration.txt)

Thanks a lot again for your help. 

Best,
Ray

**Comment by mshadbolt** [comment]
Hi Ray

It looks like your stack is running at an earlier version, do you know what overall version of CanDIGv2 is running? (I would guess maybe v.2.1.1). This version is before the date intervals, so to get test ingest files for that version you'll need to go back to the version of ingest that was compatible with the stack, i.e. v3.0.0 - https://github.com/CanDIG/candigv2-ingest/tree/v3.0.0 , rather than our latest develop branch. This will also be what is in `CanDIGv2/lib/candig-ingest/candigv2-ingest` based on the status commits you shared.

There also seems to be quite a lot of issues with the stack based on the integration test results. If tyk is not functioning properly the stack as a whole cannot function because the different services can't communicate with each other. 

If you're still at a testing stage and it is possible, you may want to consider trying to upgrade your stack to the latest stable version at v4.0.0 which supports date intervals and would make it easier for us to help with debugging.

**Comment by rjiang9** [comment]
Hi @mshadbolt ,

Sorry I don't have the info for what version our stack CanDIGv2 is running on. When I first tried, I was in the `CanDIGv2/lib/candig-ingest/candigv2-ingest`, and I notice the dates format in the `tests/clinical_ingest.json` was in string but the openapi schema.yml was an newer 'interval' version. I was confused. 

We are in the testing stage and I would talk to my colleague who worked on it for an upgrade as you suggest here once he is back. 

Thank you again and I really appreciate it. 

Sincerely,
Ray

**Comment by mshadbolt** [comment]
Hi Ray

That is totally understandable, it is very confusing dealing with the different versions of the microservices and schemas. Do reach out again if we can help again in the future.

Kind regards

Marion
